/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JobId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobIdTests
    {
        // TODO uncomment below to declare an instance variable for JobId
        //private JobId instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JobId
            //instance = new JobId();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JobId
        /// </summary>
        [Test]
        public void JobIdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JobId
            //Assert.IsInstanceOfType<JobId> (instance, "variable 'instance' is a JobId");
        }

        /// <summary>
        /// Test the property '_JobId'
        /// </summary>
        [Test]
        public void _JobIdTest()
        {
            // TODO unit test for the property '_JobId'
        }

    }

}
