/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelBreak
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelBreakTests
    {
        // TODO uncomment below to declare an instance variable for ModelBreak
        //private ModelBreak instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelBreak
            //instance = new ModelBreak();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelBreak
        /// </summary>
        [Test]
        public void ModelBreakInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelBreak
            //Assert.IsInstanceOfType<ModelBreak> (instance, "variable 'instance' is a ModelBreak");
        }

        /// <summary>
        /// Test the property 'Earliest'
        /// </summary>
        [Test]
        public void EarliestTest()
        {
            // TODO unit test for the property 'Earliest'
        }
        /// <summary>
        /// Test the property 'Latest'
        /// </summary>
        [Test]
        public void LatestTest()
        {
            // TODO unit test for the property 'Latest'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'MaxDrivingTime'
        /// </summary>
        [Test]
        public void MaxDrivingTimeTest()
        {
            // TODO unit test for the property 'MaxDrivingTime'
        }
        /// <summary>
        /// Test the property 'InitialDrivingTime'
        /// </summary>
        [Test]
        public void InitialDrivingTimeTest()
        {
            // TODO unit test for the property 'InitialDrivingTime'
        }
        /// <summary>
        /// Test the property 'PossibleSplit'
        /// </summary>
        [Test]
        public void PossibleSplitTest()
        {
            // TODO unit test for the property 'PossibleSplit'
        }

    }

}
