/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RequestTests
    {
        // TODO uncomment below to declare an instance variable for Request
        //private Request instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Request
            //instance = new Request();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Request
        /// </summary>
        [Test]
        public void RequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Request
            //Assert.IsInstanceOfType<Request> (instance, "variable 'instance' is a Request");
        }

        /// <summary>
        /// Test the property 'Vehicles'
        /// </summary>
        [Test]
        public void VehiclesTest()
        {
            // TODO unit test for the property 'Vehicles'
        }
        /// <summary>
        /// Test the property 'VehicleTypes'
        /// </summary>
        [Test]
        public void VehicleTypesTest()
        {
            // TODO unit test for the property 'VehicleTypes'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Test]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
        /// <summary>
        /// Test the property 'Shipments'
        /// </summary>
        [Test]
        public void ShipmentsTest()
        {
            // TODO unit test for the property 'Shipments'
        }
        /// <summary>
        /// Test the property 'Relations'
        /// </summary>
        [Test]
        public void RelationsTest()
        {
            // TODO unit test for the property 'Relations'
        }
        /// <summary>
        /// Test the property 'Algorithm'
        /// </summary>
        [Test]
        public void AlgorithmTest()
        {
            // TODO unit test for the property 'Algorithm'
        }
        /// <summary>
        /// Test the property 'Objectives'
        /// </summary>
        [Test]
        public void ObjectivesTest()
        {
            // TODO unit test for the property 'Objectives'
        }
        /// <summary>
        /// Test the property 'CostMatrices'
        /// </summary>
        [Test]
        public void CostMatricesTest()
        {
            // TODO unit test for the property 'CostMatrices'
        }

    }

}
