/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Route
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RouteTests
    {
        // TODO uncomment below to declare an instance variable for Route
        //private Route instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Route
            //instance = new Route();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Route
        /// </summary>
        [Test]
        public void RouteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Route
            //Assert.IsInstanceOfType<Route> (instance, "variable 'instance' is a Route");
        }

        /// <summary>
        /// Test the property 'VehicleId'
        /// </summary>
        [Test]
        public void VehicleIdTest()
        {
            // TODO unit test for the property 'VehicleId'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'TransportTime'
        /// </summary>
        [Test]
        public void TransportTimeTest()
        {
            // TODO unit test for the property 'TransportTime'
        }
        /// <summary>
        /// Test the property 'CompletionTime'
        /// </summary>
        [Test]
        public void CompletionTimeTest()
        {
            // TODO unit test for the property 'CompletionTime'
        }
        /// <summary>
        /// Test the property 'WaitingTime'
        /// </summary>
        [Test]
        public void WaitingTimeTest()
        {
            // TODO unit test for the property 'WaitingTime'
        }
        /// <summary>
        /// Test the property 'Activities'
        /// </summary>
        [Test]
        public void ActivitiesTest()
        {
            // TODO unit test for the property 'Activities'
        }

    }

}
