/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Solution
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SolutionTests
    {
        // TODO uncomment below to declare an instance variable for Solution
        //private Solution instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Solution
            //instance = new Solution();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Solution
        /// </summary>
        [Test]
        public void SolutionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Solution
            //Assert.IsInstanceOfType<Solution> (instance, "variable 'instance' is a Solution");
        }

        /// <summary>
        /// Test the property 'Costs'
        /// </summary>
        [Test]
        public void CostsTest()
        {
            // TODO unit test for the property 'Costs'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'NoUnassigned'
        /// </summary>
        [Test]
        public void NoUnassignedTest()
        {
            // TODO unit test for the property 'NoUnassigned'
        }
        /// <summary>
        /// Test the property 'Routes'
        /// </summary>
        [Test]
        public void RoutesTest()
        {
            // TODO unit test for the property 'Routes'
        }
        /// <summary>
        /// Test the property 'Unassigned'
        /// </summary>
        [Test]
        public void UnassignedTest()
        {
            // TODO unit test for the property 'Unassigned'
        }

    }

}
