/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TimeWindow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimeWindowTests
    {
        // TODO uncomment below to declare an instance variable for TimeWindow
        //private TimeWindow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TimeWindow
            //instance = new TimeWindow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimeWindow
        /// </summary>
        [Test]
        public void TimeWindowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TimeWindow
            //Assert.IsInstanceOfType<TimeWindow> (instance, "variable 'instance' is a TimeWindow");
        }

        /// <summary>
        /// Test the property 'Earliest'
        /// </summary>
        [Test]
        public void EarliestTest()
        {
            // TODO unit test for the property 'Earliest'
        }
        /// <summary>
        /// Test the property 'Latest'
        /// </summary>
        [Test]
        public void LatestTest()
        {
            // TODO unit test for the property 'Latest'
        }

    }

}
