/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Vehicle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleTests
    {
        // TODO uncomment below to declare an instance variable for Vehicle
        //private Vehicle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Vehicle
            //instance = new Vehicle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Vehicle
        /// </summary>
        [Test]
        public void VehicleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Vehicle
            //Assert.IsInstanceOfType<Vehicle> (instance, "variable 'instance' is a Vehicle");
        }

        /// <summary>
        /// Test the property 'VehicleId'
        /// </summary>
        [Test]
        public void VehicleIdTest()
        {
            // TODO unit test for the property 'VehicleId'
        }
        /// <summary>
        /// Test the property 'TypeId'
        /// </summary>
        [Test]
        public void TypeIdTest()
        {
            // TODO unit test for the property 'TypeId'
        }
        /// <summary>
        /// Test the property 'StartAddress'
        /// </summary>
        [Test]
        public void StartAddressTest()
        {
            // TODO unit test for the property 'StartAddress'
        }
        /// <summary>
        /// Test the property 'EndAddress'
        /// </summary>
        [Test]
        public void EndAddressTest()
        {
            // TODO unit test for the property 'EndAddress'
        }
        /// <summary>
        /// Test the property '_Break'
        /// </summary>
        [Test]
        public void _BreakTest()
        {
            // TODO unit test for the property '_Break'
        }
        /// <summary>
        /// Test the property 'ReturnToDepot'
        /// </summary>
        [Test]
        public void ReturnToDepotTest()
        {
            // TODO unit test for the property 'ReturnToDepot'
        }
        /// <summary>
        /// Test the property 'EarliestStart'
        /// </summary>
        [Test]
        public void EarliestStartTest()
        {
            // TODO unit test for the property 'EarliestStart'
        }
        /// <summary>
        /// Test the property 'LatestEnd'
        /// </summary>
        [Test]
        public void LatestEndTest()
        {
            // TODO unit test for the property 'LatestEnd'
        }
        /// <summary>
        /// Test the property 'Skills'
        /// </summary>
        [Test]
        public void SkillsTest()
        {
            // TODO unit test for the property 'Skills'
        }

    }

}
