/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VehicleType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleTypeTests
    {
        // TODO uncomment below to declare an instance variable for VehicleType
        //private VehicleType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VehicleType
            //instance = new VehicleType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VehicleType
        /// </summary>
        [Test]
        public void VehicleTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VehicleType
            //Assert.IsInstanceOfType<VehicleType> (instance, "variable 'instance' is a VehicleType");
        }

        /// <summary>
        /// Test the property 'TypeId'
        /// </summary>
        [Test]
        public void TypeIdTest()
        {
            // TODO unit test for the property 'TypeId'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'Capacity'
        /// </summary>
        [Test]
        public void CapacityTest()
        {
            // TODO unit test for the property 'Capacity'
        }
        /// <summary>
        /// Test the property 'SpeedFactor'
        /// </summary>
        [Test]
        public void SpeedFactorTest()
        {
            // TODO unit test for the property 'SpeedFactor'
        }
        /// <summary>
        /// Test the property 'ServiceTimeFactor'
        /// </summary>
        [Test]
        public void ServiceTimeFactorTest()
        {
            // TODO unit test for the property 'ServiceTimeFactor'
        }

    }

}
