#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGAddress
@end

@interface SWGAddress : SWGObject

/* Unique identifier of location [optional]
 */
@property(nonatomic) NSString* locationId;
/* longitude [optional]
 */
@property(nonatomic) NSNumber* lon;
/* latitude [optional]
 */
@property(nonatomic) NSNumber* lat;

@end
