#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGBreak
@end

@interface SWGBreak : SWGObject

/* earliest start of break [optional]
 */
@property(nonatomic) NSNumber* earliest;
/* latest start of break [optional]
 */
@property(nonatomic) NSNumber* latest;
/* duration of break [optional]
 */
@property(nonatomic) NSNumber* duration;
/* max driving time without break [optional]
 */
@property(nonatomic) NSNumber* maxDrivingTime;
/* initial driving time, i.e. the time your driver has already spent for driving [optional]
 */
@property(nonatomic) NSNumber* initialDrivingTime;
/* array of splits [optional]
 */
@property(nonatomic) NSArray<NSNumber*>* possibleSplit;

@end
