#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCostMatrix
@end

@interface SWGCostMatrix : SWGObject

/* type of cost matrix, currently default or google are supported [optional]
 */
@property(nonatomic) NSString* type;
/* URL of matrix service [optional]
 */
@property(nonatomic) NSString* url;
/* vehicle profile or empty if catch all fallback [optional]
 */
@property(nonatomic) NSString* profile;

@end
