#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGObjective
@end

@interface SWGObjective : SWGObject

/* type of objective function, i.e. min or min-max  [optional]
 */
@property(nonatomic) NSString* type;
/* objective function value [optional]
 */
@property(nonatomic) NSString* value;

@end
