#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGActivity.h"


@protocol SWGRoute
@end

@interface SWGRoute : SWGObject

/* id of vehicle that operates route [optional]
 */
@property(nonatomic) NSString* vehicleId;
/* distance of route in meter [optional]
 */
@property(nonatomic) NSNumber* distance;
/* transport time of route in ms [optional]
 */
@property(nonatomic) NSNumber* transportTime;
/* completion time of route in ms [optional]
 */
@property(nonatomic) NSNumber* completionTime;
/* waiting time of route in ms [optional]
 */
@property(nonatomic) NSNumber* waitingTime;
/* array of activities [optional]
 */
@property(nonatomic) NSArray<SWGActivity>* activities;

@end
