#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAlgorithm.h"
#import "SWGCostMatrix.h"
#import "SWGObjective.h"
#import "SWGRelation.h"
#import "SWGService.h"
#import "SWGShipment.h"
#import "SWGVehicle.h"
#import "SWGVehicleType.h"


@protocol SWGRequest
@end

@interface SWGRequest : SWGObject

/* An array of vehicles that can be employed [optional]
 */
@property(nonatomic) NSArray<SWGVehicle>* vehicles;
/* An array of vehicle types [optional]
 */
@property(nonatomic) NSArray<SWGVehicleType>* vehicleTypes;
/* An array of services [optional]
 */
@property(nonatomic) NSArray<SWGService>* services;
/* An array of shipments [optional]
 */
@property(nonatomic) NSArray<SWGShipment>* shipments;
/* An array of relations [optional]
 */
@property(nonatomic) NSArray<SWGRelation>* relations;

@property(nonatomic) SWGAlgorithm* algorithm;
/* An array of objectives [optional]
 */
@property(nonatomic) NSArray<SWGObjective>* objectives;
/* An array of cost matrices [optional]
 */
@property(nonatomic) NSArray<SWGCostMatrix>* costMatrices;

@end
