#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGRelation
@end

@interface SWGRelation : SWGObject

/* identifier of relation [optional]
 */
@property(nonatomic) NSString* type;
/* An array of ids that should be related [optional]
 */
@property(nonatomic) NSArray<NSString*>* ids;
/* vehicle id [optional]
 */
@property(nonatomic) NSString* vehicleId;

@end
