#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAddress.h"
#import "SWGTimeWindow.h"


@protocol SWGStop
@end

@interface SWGStop : SWGObject


@property(nonatomic) SWGAddress* address;
/* duration of stop, i.e. time in ms the corresponding activity takes [optional]
 */
@property(nonatomic) NSNumber* duration;
/* array of time windows. currently, only a single time window is allowed [optional]
 */
@property(nonatomic) NSArray<SWGTimeWindow>* timeWindows;

@end
