#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGRoute.h"
#import "SWGSolutionUnassigned.h"


@protocol SWGSolution
@end

@interface SWGSolution : SWGObject

/* overall costs of solution [optional]
 */
@property(nonatomic) NSNumber* costs;
/* overall travel distance in meters [optional]
 */
@property(nonatomic) NSNumber* distance;
/* overall transport time in ms [optional]
 */
@property(nonatomic) NSNumber* time;
/* overall transport time in ms [optional]
 */
@property(nonatomic) NSNumber* transportTime;
/* operation time of the longest route in ms [optional]
 */
@property(nonatomic) NSNumber* maxOperationTime;
/* total waiting time in ms [optional]
 */
@property(nonatomic) NSNumber* waitingTime;
/* number of employed vehicles [optional]
 */
@property(nonatomic) NSNumber* noVehicles;
/* number of jobs that could not be assigned to final solution [optional]
 */
@property(nonatomic) NSNumber* noUnassigned;
/* An array of routes [optional]
 */
@property(nonatomic) NSArray<SWGRoute>* routes;

@property(nonatomic) SWGSolutionUnassigned* unassigned;

@end
