<?php
/**
 * RequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestTest Class Doc Comment
 *
 * @category    Class */
// * @description Request
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Request"
     */
    public function testRequest()
    {

    }

    /**
     * Test attribute "vehicles"
     */
    public function testPropertyVehicles()
    {

    }

    /**
     * Test attribute "vehicle_types"
     */
    public function testPropertyVehicleTypes()
    {

    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {

    }

    /**
     * Test attribute "shipments"
     */
    public function testPropertyShipments()
    {

    }

    /**
     * Test attribute "relations"
     */
    public function testPropertyRelations()
    {

    }

    /**
     * Test attribute "algorithm"
     */
    public function testPropertyAlgorithm()
    {

    }

    /**
     * Test attribute "objectives"
     */
    public function testPropertyObjectives()
    {

    }

    /**
     * Test attribute "cost_matrices"
     */
    public function testPropertyCostMatrices()
    {

    }

}
