<?php
/**
 * SolutionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SolutionTest Class Doc Comment
 *
 * @category    Class */
// * @description Solution
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SolutionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Solution"
     */
    public function testSolution()
    {

    }

    /**
     * Test attribute "costs"
     */
    public function testPropertyCosts()
    {

    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {

    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {

    }

    /**
     * Test attribute "transport_time"
     */
    public function testPropertyTransportTime()
    {

    }

    /**
     * Test attribute "max_operation_time"
     */
    public function testPropertyMaxOperationTime()
    {

    }

    /**
     * Test attribute "waiting_time"
     */
    public function testPropertyWaitingTime()
    {

    }

    /**
     * Test attribute "no_vehicles"
     */
    public function testPropertyNoVehicles()
    {

    }

    /**
     * Test attribute "no_unassigned"
     */
    public function testPropertyNoUnassigned()
    {

    }

    /**
     * Test attribute "routes"
     */
    public function testPropertyRoutes()
    {

    }

    /**
     * Test attribute "unassigned"
     */
    public function testPropertyUnassigned()
    {

    }

}
