/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model




case class Activity (
  /* type of activity */
  _type: String,
/* id referring to the underlying service or shipment, i.e. the shipment or service this activity belongs to */
  id: String,
/* id that refers to address */
  locationId: String,
/* arrival time at this activity in ms */
  arrTime: Long,
/* end time of and thus departure time at this activity */
  endTime: Long,
/* waiting time at this activity in ms */
  waitingTime: Long,
/* cumulated distance from start to this activity in m */
  distance: Long,
/* driving time of driver in ms */
  drivingTime: Long,
/* Array with size/capacity dimensions before this activity */
  loadBefore: List[Integer],
/* Array with size/capacity dimensions after this activity */
  loadAfter: List[Integer])
