/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class CostMatrix (
  /* type of cost matrix, currently default or google are supported */
  _type: String,
  /* URL of matrix service */
  url: String,
  /* vehicle profile or empty if catch all fallback */
  profile: String
)
