/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model




case class Request (
  /* An array of vehicles that can be employed */
  vehicles: List[Vehicle],
/* An array of vehicle types */
  vehicleTypes: List[VehicleType],
/* An array of services */
  services: List[Service],
/* An array of shipments */
  shipments: List[Shipment],
/* An array of relations */
  relations: List[Relation],
algorithm: Algorithm,
/* An array of objectives */
  objectives: List[Objective],
/* An array of cost matrices */
  costMatrices: List[CostMatrix])
