/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class Response (
  copyrights: List[String],
  /* unique identify of job - which you get when posting your request to the large problem solver */
  jobId: String,
  /* indicates the current status of the job */
  status: String,
  /* waiting time in ms */
  waitingInQueue: Long,
  /* processing time in ms. if job is still waiting in queue, processing_time is 0 */
  processingTime: Long,
  /* the solution. only available if status field indicates finished */
  solution: Solution
)
