/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class Route (
  /* id of vehicle that operates route */
  vehicleId: String,
  /* distance of route in meter */
  distance: Long,
  /* transport time of route in ms */
  transportTime: Long,
  /* completion time of route in ms */
  completionTime: Long,
  /* waiting time of route in ms */
  waitingTime: Long,
  /* array of activities */
  activities: List[Activity]
)
