/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model




case class Solution (
  /* overall costs of solution */
  costs: Integer,
/* overall travel distance in meters */
  distance: Integer,
/* overall transport time in ms */
  time: Long,
/* overall transport time in ms */
  transportTime: Long,
/* operation time of the longest route in ms */
  maxOperationTime: Long,
/* total waiting time in ms */
  waitingTime: Long,
/* number of employed vehicles */
  noVehicles: Integer,
/* number of jobs that could not be assigned to final solution */
  noUnassigned: Integer,
/* An array of routes */
  routes: List[Route],
unassigned: SolutionUnassigned)
