/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class VehicleType (
  /* Unique identifier for the vehicle type */
  typeId: String,
  /* Profile of vehicle type */
  profile: String,
  /* array of capacity dimensions */
  capacity: List[Integer],
  /* speed_factor of vehicle type */
  speedFactor: Double,
  /* service time factor of vehicle type */
  serviceTimeFactor: Double
)
