package WWW::SwaggerClient::Object::Activity;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'type' => 'string',
    'id' => 'string',
    'location_id' => 'string',
    'arr_time' => 'int',
    'end_time' => 'int'
};

my $attribute_map = {
    'type' => 'type',
    'id' => 'id',
    'location_id' => 'location_id',
    'arr_time' => 'arr_time',
    'end_time' => 'end_time'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #type of activity
        'type' => $args{'type'}, 
        #id referring to the underlying service or shipment, i.e. the shipment or service this activity belongs to
        'id' => $args{'id'}, 
        #id that refers to address
        'location_id' => $args{'location_id'}, 
        #arrival time at this activity in ms
        'arr_time' => $args{'arr_time'}, 
        #end time of and thus departure time at this activity
        'end_time' => $args{'end_time'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
