package WWW::SwaggerClient::Object::Address;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'location_id' => 'string',
    'lon' => 'double',
    'lat' => 'double'
};

my $attribute_map = {
    'location_id' => 'location_id',
    'lon' => 'lon',
    'lat' => 'lat'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Unique identifier of location
        'location_id' => $args{'location_id'}, 
        #longitude
        'lon' => $args{'lon'}, 
        #latitude
        'lat' => $args{'lat'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
