package WWW::SwaggerClient::Object::Break;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'earliest' => 'int',
    'latest' => 'int',
    'duration' => 'int'
};

my $attribute_map = {
    'earliest' => 'earliest',
    'latest' => 'latest',
    'duration' => 'duration'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #earliest start of break
        'earliest' => $args{'earliest'}, 
        #latest start of break
        'latest' => $args{'latest'}, 
        #duration of break
        'duration' => $args{'duration'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
