package WWW::SwaggerClient::Object::Relation;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'type' => 'string',
    'ids' => 'ARRAY[string]',
    'vehicle_id' => 'string'
};

my $attribute_map = {
    'type' => 'type',
    'ids' => 'ids',
    'vehicle_id' => 'vehicle_id'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #identifier of relation
        'type' => $args{'type'}, 
        #An array of ids that should be related
        'ids' => $args{'ids'}, 
        #vehicle id
        'vehicle_id' => $args{'vehicle_id'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
