package WWW::SwaggerClient::Object::Service;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'id' => 'string',
    'type' => 'string',
    'name' => 'string',
    'address' => 'Address',
    'duration' => 'int',
    'time_windows' => 'ARRAY[TimeWindow]',
    'size' => 'ARRAY[int]',
    'required_skills' => 'ARRAY[string]',
    'allowed_vehicles' => 'ARRAY[string]'
};

my $attribute_map = {
    'id' => 'id',
    'type' => 'type',
    'name' => 'name',
    'address' => 'address',
    'duration' => 'duration',
    'time_windows' => 'time_windows',
    'size' => 'size',
    'required_skills' => 'required_skills',
    'allowed_vehicles' => 'allowed_vehicles'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Unique identifier of service
        'id' => $args{'id'}, 
        #type of service
        'type' => $args{'type'}, 
        #name of service
        'name' => $args{'name'}, 
        #
        'address' => $args{'address'}, 
        #duration of service, i.e. time in ms the corresponding activity takes
        'duration' => $args{'duration'}, 
        #array of time windows. currently, only a single time window is allowed
        'time_windows' => $args{'time_windows'}, 
        #array of capacity dimensions
        'size' => $args{'size'}, 
        #array of required skills
        'required_skills' => $args{'required_skills'}, 
        #array of allowed vehicle ids
        'allowed_vehicles' => $args{'allowed_vehicles'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
