package WWW::SwaggerClient::Object::Solution;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'costs' => 'int',
    'distance' => 'int',
    'time' => 'int',
    'no_unassigned' => 'int',
    'routes' => 'ARRAY[Route]',
    'unassigned' => 'object'
};

my $attribute_map = {
    'costs' => 'costs',
    'distance' => 'distance',
    'time' => 'time',
    'no_unassigned' => 'no_unassigned',
    'routes' => 'routes',
    'unassigned' => 'unassigned'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #overall costs of solution
        'costs' => $args{'costs'}, 
        #overall travel distance in meters
        'distance' => $args{'distance'}, 
        #overall travel time in ms
        'time' => $args{'time'}, 
        #number of jobs that could not be assigned to final solution
        'no_unassigned' => $args{'no_unassigned'}, 
        #An array of routes
        'routes' => $args{'routes'}, 
        #
        'unassigned' => $args{'unassigned'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
