package WWW::SwaggerClient::Object::Stop;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'address' => 'Address',
    'duration' => 'int',
    'time_windows' => 'ARRAY[TimeWindow]'
};

my $attribute_map = {
    'address' => 'address',
    'duration' => 'duration',
    'time_windows' => 'time_windows'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #
        'address' => $args{'address'}, 
        #duration of stop, i.e. time in ms the corresponding activity takes
        'duration' => $args{'duration'}, 
        #array of time windows. currently, only a single time window is allowed
        'time_windows' => $args{'time_windows'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
