package WWW::SwaggerClient::Object::VehicleType;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'type_id' => 'string',
    'profile' => 'string',
    'capacity' => 'ARRAY[int]',
    'speed_factor' => 'double',
    'service_time_factor' => 'double'
};

my $attribute_map = {
    'type_id' => 'type_id',
    'profile' => 'profile',
    'capacity' => 'capacity',
    'speed_factor' => 'speed_factor',
    'service_time_factor' => 'service_time_factor'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Unique identifier for the vehicle type
        'type_id' => $args{'type_id'}, 
        #Profile of vehicle type
        'profile' => $args{'profile'}, 
        #array of capacity dimensions
        'capacity' => $args{'capacity'}, 
        #speed_factor of vehicle type
        'speed_factor' => $args{'speed_factor'}, 
        #service time factor of vehicle type
        'service_time_factor' => $args{'service_time_factor'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
