/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Algorithm
    /// </summary>
    [DataContract]
    public partial class Algorithm :  IEquatable<Algorithm>
    {
        /// <summary>
        /// Gets or Sets ProblemType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProblemTypeEnum
        {
            
            /// <summary>
            /// Enum Min for "min"
            /// </summary>
            [EnumMember(Value = "min")]
            Min,
            
            /// <summary>
            /// Enum Minmax for "min-max"
            /// </summary>
            [EnumMember(Value = "min-max")]
            Minmax
        }

        /// <summary>
        /// Gets or Sets Objective
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ObjectiveEnum
        {
            
            /// <summary>
            /// Enum Transporttime for "transport_time"
            /// </summary>
            [EnumMember(Value = "transport_time")]
            Transporttime,
            
            /// <summary>
            /// Enum Completiontime for "completion_time"
            /// </summary>
            [EnumMember(Value = "completion_time")]
            Completiontime
        }

        /// <summary>
        /// Gets or Sets ProblemType
        /// </summary>
        [DataMember(Name="problem_type", EmitDefaultValue=false)]
        public ProblemTypeEnum? ProblemType { get; set; }
        /// <summary>
        /// Gets or Sets Objective
        /// </summary>
        [DataMember(Name="objective", EmitDefaultValue=false)]
        public ObjectiveEnum? Objective { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Algorithm" /> class.
        /// </summary>
        /// <param name="ProblemType">ProblemType.</param>
        /// <param name="Objective">Objective.</param>
        public Algorithm(ProblemTypeEnum? ProblemType = null, ObjectiveEnum? Objective = null)
        {
            this.ProblemType = ProblemType;
            this.Objective = Objective;
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Algorithm {\n");
            sb.Append("  ProblemType: ").Append(ProblemType).Append("\n");
            sb.Append("  Objective: ").Append(Objective).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Algorithm);
        }

        /// <summary>
        /// Returns true if Algorithm instances are equal
        /// </summary>
        /// <param name="other">Instance of Algorithm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Algorithm other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ProblemType == other.ProblemType ||
                    this.ProblemType != null &&
                    this.ProblemType.Equals(other.ProblemType)
                ) && 
                (
                    this.Objective == other.Objective ||
                    this.Objective != null &&
                    this.Objective.Equals(other.Objective)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ProblemType != null)
                    hash = hash * 59 + this.ProblemType.GetHashCode();
                if (this.Objective != null)
                    hash = hash * 59 + this.Objective.GetHashCode();
                return hash;
            }
        }
    }

}
