// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}

public class Response<T> {
    public let statusCode: Int
    public let header: [String: String]
    public let body: T

    public init(statusCode: Int, header: [String: String], body: T) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: NSHTTPURLResponse, body: T) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = dispatch_once_t()
class Decoders {
    static private var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()
    
    static func addDecoder<T>(clazz clazz: T.Type, decoder: ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as! AnyObject }
    }
    
    static func decode<T>(clazz clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }
    
    static func decode<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictinoary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictinoary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }
    
    static func decode<T>(clazz clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if source is T {
            return source as! T
        }
        
        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }
	
    static private func initialize() {
        dispatch_once(&once) {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'"
            ].map { (format: String) -> NSDateFormatter in
                let formatter = NSDateFormatter()
                formatter.dateFormat = format
                return formatter
            }
            // Decoder for NSDate
            Decoders.addDecoder(clazz: NSDate.self) { (source: AnyObject) -> NSDate in
                let sourceString = source as! String
                for formatter in formatters {
                    if let date = formatter.dateFromString(sourceString) {
                        return date
                    }
                }
                fatalError("formatter failed to parse \(sourceString)")
            } 

			// Decoder for [JobId]
            Decoders.addDecoder(clazz: [JobId].self) { (source: AnyObject) -> [JobId] in
                return Decoders.decode(clazz: [JobId].self, source: source)
            }
			// Decoder for JobId
            Decoders.addDecoder(clazz: JobId.self) { (source: AnyObject) -> JobId in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = JobId()
                instance.job_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["job_id"])
                return instance
            }
			

			// Decoder for [Request]
            Decoders.addDecoder(clazz: [Request].self) { (source: AnyObject) -> [Request] in
                return Decoders.decode(clazz: [Request].self, source: source)
            }
			// Decoder for Request
            Decoders.addDecoder(clazz: Request.self) { (source: AnyObject) -> Request in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Request()
                instance.vehicles = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["vehicles"])
                instance.vehicle_types = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["vehicle_types"])
                instance.services = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["services"])
                instance.shipments = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["shipments"])
                instance.relations = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["relations"])
                instance.algorithm = Decoders.decodeOptional(clazz: Algorithm.self, source: sourceDictionary["algorithm"])
                return instance
            }
			

			// Decoder for [Vehicle]
            Decoders.addDecoder(clazz: [Vehicle].self) { (source: AnyObject) -> [Vehicle] in
                return Decoders.decode(clazz: [Vehicle].self, source: source)
            }
			// Decoder for Vehicle
            Decoders.addDecoder(clazz: Vehicle.self) { (source: AnyObject) -> Vehicle in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Vehicle()
                instance.vehicle_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["vehicle_id"])
                instance.type_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type_id"])
                instance.start_address = Decoders.decodeOptional(clazz: Address.self, source: sourceDictionary["start_address"])
                instance.end_address = Decoders.decodeOptional(clazz: Address.self, source: sourceDictionary["end_address"])
                instance.Swaggerbreak = Decoders.decodeOptional(clazz: Break.self, source: sourceDictionary["Swaggerbreak"])
                instance.return_to_depot = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["return_to_depot"])
                instance.earliest_start = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["earliest_start"])
                instance.latest_end = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["latest_end"])
                instance.skills = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["skills"])
                return instance
            }
			

			// Decoder for [Algorithm]
            Decoders.addDecoder(clazz: [Algorithm].self) { (source: AnyObject) -> [Algorithm] in
                return Decoders.decode(clazz: [Algorithm].self, source: source)
            }
			// Decoder for Algorithm
            Decoders.addDecoder(clazz: Algorithm.self) { (source: AnyObject) -> Algorithm in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Algorithm()
                instance.problem_type = (sourceDictionary["problem_type"] as? String).map { Algorithm.Problem_type(rawValue: $0)! } 
                instance.objective = (sourceDictionary["objective"] as? String).map { Algorithm.Objective(rawValue: $0)! } 
                return instance
            }
			

			// Decoder for [Address]
            Decoders.addDecoder(clazz: [Address].self) { (source: AnyObject) -> [Address] in
                return Decoders.decode(clazz: [Address].self, source: source)
            }
			// Decoder for Address
            Decoders.addDecoder(clazz: Address.self) { (source: AnyObject) -> Address in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Address()
                instance.location_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["location_id"])
                instance.lon = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["lon"])
                instance.lat = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["lat"])
                return instance
            }
			

			// Decoder for [Break]
            Decoders.addDecoder(clazz: [Break].self) { (source: AnyObject) -> [Break] in
                return Decoders.decode(clazz: [Break].self, source: source)
            }
			// Decoder for Break
            Decoders.addDecoder(clazz: Break.self) { (source: AnyObject) -> Break in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Break()
                instance.earliest = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["earliest"])
                instance.latest = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["latest"])
                instance.duration = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["duration"])
                return instance
            }
			

			// Decoder for [VehicleType]
            Decoders.addDecoder(clazz: [VehicleType].self) { (source: AnyObject) -> [VehicleType] in
                return Decoders.decode(clazz: [VehicleType].self, source: source)
            }
			// Decoder for VehicleType
            Decoders.addDecoder(clazz: VehicleType.self) { (source: AnyObject) -> VehicleType in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = VehicleType()
                instance.type_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type_id"])
                instance.profile = (sourceDictionary["profile"] as? String).map { VehicleType.Profile(rawValue: $0)! } 
                instance.capacity = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["capacity"])
                instance.speed_factor = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["speed_factor"])
                instance.service_time_factor = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["service_time_factor"])
                return instance
            }
			

			// Decoder for [Service]
            Decoders.addDecoder(clazz: [Service].self) { (source: AnyObject) -> [Service] in
                return Decoders.decode(clazz: [Service].self, source: source)
            }
			// Decoder for Service
            Decoders.addDecoder(clazz: Service.self) { (source: AnyObject) -> Service in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Service()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.type = (sourceDictionary["type"] as? String).map { Service.SwaggerType(rawValue: $0)! } 
                instance.priority = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["priority"])
                instance.name = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"])
                instance.address = Decoders.decodeOptional(clazz: Address.self, source: sourceDictionary["address"])
                instance.duration = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["duration"])
                instance.time_windows = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["time_windows"])
                instance.size = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["size"])
                instance.required_skills = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["required_skills"])
                instance.allowed_vehicles = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["allowed_vehicles"])
                return instance
            }
			

			// Decoder for [Shipment]
            Decoders.addDecoder(clazz: [Shipment].self) { (source: AnyObject) -> [Shipment] in
                return Decoders.decode(clazz: [Shipment].self, source: source)
            }
			// Decoder for Shipment
            Decoders.addDecoder(clazz: Shipment.self) { (source: AnyObject) -> Shipment in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Shipment()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.name = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"])
                instance.priority = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["priority"])
                instance.pickup = Decoders.decodeOptional(clazz: Stop.self, source: sourceDictionary["pickup"])
                instance.delivery = Decoders.decodeOptional(clazz: Stop.self, source: sourceDictionary["delivery"])
                instance.size = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["size"])
                instance.required_skills = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["required_skills"])
                instance.allowed_vehicles = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["allowed_vehicles"])
                return instance
            }
			

			// Decoder for [Stop]
            Decoders.addDecoder(clazz: [Stop].self) { (source: AnyObject) -> [Stop] in
                return Decoders.decode(clazz: [Stop].self, source: source)
            }
			// Decoder for Stop
            Decoders.addDecoder(clazz: Stop.self) { (source: AnyObject) -> Stop in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Stop()
                instance.address = Decoders.decodeOptional(clazz: Address.self, source: sourceDictionary["address"])
                instance.duration = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["duration"])
                instance.time_windows = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["time_windows"])
                return instance
            }
			

			// Decoder for [TimeWindow]
            Decoders.addDecoder(clazz: [TimeWindow].self) { (source: AnyObject) -> [TimeWindow] in
                return Decoders.decode(clazz: [TimeWindow].self, source: source)
            }
			// Decoder for TimeWindow
            Decoders.addDecoder(clazz: TimeWindow.self) { (source: AnyObject) -> TimeWindow in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TimeWindow()
                instance.earliest = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["earliest"])
                instance.latest = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["latest"])
                return instance
            }
			

			// Decoder for [Relation]
            Decoders.addDecoder(clazz: [Relation].self) { (source: AnyObject) -> [Relation] in
                return Decoders.decode(clazz: [Relation].self, source: source)
            }
			// Decoder for Relation
            Decoders.addDecoder(clazz: Relation.self) { (source: AnyObject) -> Relation in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Relation()
                instance.type = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"])
                instance.ids = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["ids"])
                instance.vehicle_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["vehicle_id"])
                return instance
            }
			

			// Decoder for [Response]
            Decoders.addDecoder(clazz: [Response].self) { (source: AnyObject) -> [Response] in
                return Decoders.decode(clazz: [Response].self, source: source)
            }
			// Decoder for Response
            Decoders.addDecoder(clazz: Response.self) { (source: AnyObject) -> Response in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Response()
                instance.job_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["job_id"])
                instance.status = (sourceDictionary["status"] as? String).map { Response.Status(rawValue: $0)! } 
                instance.waiting_in_queue = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["waiting_in_queue"])
                instance.processing_time = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["processing_time"])
                instance.solution = Decoders.decodeOptional(clazz: Solution.self, source: sourceDictionary["solution"])
                return instance
            }
			

			// Decoder for [Solution]
            Decoders.addDecoder(clazz: [Solution].self) { (source: AnyObject) -> [Solution] in
                return Decoders.decode(clazz: [Solution].self, source: source)
            }
			// Decoder for Solution
            Decoders.addDecoder(clazz: Solution.self) { (source: AnyObject) -> Solution in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Solution()
                instance.costs = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["costs"])
                instance.distance = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["distance"])
                instance.time = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["time"])
                instance.no_unassigned = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["no_unassigned"])
                instance.routes = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["routes"])
                instance.unassigned = Decoders.decodeOptional(clazz: Solution_unassigned.self, source: sourceDictionary["unassigned"])
                return instance
            }
			

			// Decoder for [Route]
            Decoders.addDecoder(clazz: [Route].self) { (source: AnyObject) -> [Route] in
                return Decoders.decode(clazz: [Route].self, source: source)
            }
			// Decoder for Route
            Decoders.addDecoder(clazz: Route.self) { (source: AnyObject) -> Route in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Route()
                instance.vehicle_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["vehicle_id"])
                instance.activities = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["activities"])
                return instance
            }
			

			// Decoder for [Activity]
            Decoders.addDecoder(clazz: [Activity].self) { (source: AnyObject) -> [Activity] in
                return Decoders.decode(clazz: [Activity].self, source: source)
            }
			// Decoder for Activity
            Decoders.addDecoder(clazz: Activity.self) { (source: AnyObject) -> Activity in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Activity()
                instance.type = (sourceDictionary["type"] as? String).map { Activity.SwaggerType(rawValue: $0)! } 
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.location_id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["location_id"])
                instance.arr_time = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["arr_time"])
                instance.end_time = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["end_time"])
                return instance
            }
			

			// Decoder for [Solution_unassigned]
            Decoders.addDecoder(clazz: [Solution_unassigned].self) { (source: AnyObject) -> [Solution_unassigned] in
                return Decoders.decode(clazz: [Solution_unassigned].self, source: source)
            }
			// Decoder for Solution_unassigned
            Decoders.addDecoder(clazz: Solution_unassigned.self) { (source: AnyObject) -> Solution_unassigned in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Solution_unassigned()
                instance.services = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["services"])
                instance.shipments = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["shipments"])
                return instance
            }
			
        }
    }
}
