#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGActivity
@end

@interface SWGActivity : SWGObject

/* type of activity [optional]
 */
@property(nonatomic) NSString* type;
/* id referring to the underlying service or shipment, i.e. the shipment or service this activity belongs to [optional]
 */
@property(nonatomic) NSString* _id;
/* id that refers to address [optional]
 */
@property(nonatomic) NSString* locationId;
/* arrival time at this activity in ms [optional]
 */
@property(nonatomic) NSNumber* arrTime;
/* end time of and thus departure time at this activity [optional]
 */
@property(nonatomic) NSNumber* endTime;

@end
