#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGAddress
@end

@interface SWGAddress : SWGObject

/* Unique identifier of location [optional]
 */
@property(nonatomic) NSString* locationId;
/* longitude [optional]
 */
@property(nonatomic) NSNumber* lon;
/* latitude [optional]
 */
@property(nonatomic) NSNumber* lat;

@end
