#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGAlgorithm
@end

@interface SWGAlgorithm : SWGObject


@property(nonatomic) NSString* problemType;

@property(nonatomic) NSString* objective;

@end
