#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGJobId
@end

@interface SWGJobId : SWGObject

/* unique id for your job/request with which you can fetch your solution [optional]
 */
@property(nonatomic) NSString* jobId;

@end
