#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGActivity.h"


@protocol SWGRoute
@end

@interface SWGRoute : SWGObject

/* id of vehicle that operates route [optional]
 */
@property(nonatomic) NSString* vehicleId;
/* array of activities [optional]
 */
@property(nonatomic) NSArray<SWGActivity>* activities;

@end
