#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGSolution.h"


@protocol SWGResponse
@end

@interface SWGResponse : SWGObject

/* unique identify of job - which you get when posting your request to the large problem solver [optional]
 */
@property(nonatomic) NSString* jobId;
/* indicates the current status of the job [optional]
 */
@property(nonatomic) NSString* status;
/* waiting time in ms [optional]
 */
@property(nonatomic) NSNumber* waitingInQueue;
/* processing time in ms. if job is still waiting in queue, processing_time is 0 [optional]
 */
@property(nonatomic) NSNumber* processingTime;
/* the solution. only available if status field indicates finished [optional]
 */
@property(nonatomic) SWGSolution* solution;

@end
