#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGVehicleType.h"
#import "SWGService.h"
#import "SWGRelation.h"
#import "SWGAlgorithm.h"
#import "SWGShipment.h"
#import "SWGVehicle.h"


@protocol SWGRequest
@end

@interface SWGRequest : SWGObject

/* An array of vehicles that can be employed [optional]
 */
@property(nonatomic) NSArray<SWGVehicle>* vehicles;
/* An array of vehicle types [optional]
 */
@property(nonatomic) NSArray<SWGVehicleType>* vehicleTypes;
/* An array of services [optional]
 */
@property(nonatomic) NSArray<SWGService>* services;
/* An array of shipments [optional]
 */
@property(nonatomic) NSArray<SWGShipment>* shipments;
/* An array of relations [optional]
 */
@property(nonatomic) NSArray<SWGRelation>* relations;

@property(nonatomic) SWGAlgorithm* algorithm;

@end
