#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGSolutionUnassigned
@end

@interface SWGSolutionUnassigned : SWGObject

/* An array of ids of unassigned services [optional]
 */
@property(nonatomic) NSArray* /* NSString */ services;
/* An array of ids of unassigned shipments [optional]
 */
@property(nonatomic) NSArray* /* NSString */ shipments;

@end
