#import <Foundation/Foundation.h>
#import "SWGResponse.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGSolutionApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGSolutionApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGSolutionApi*) sharedAPI;
///
///
/// Return the solution associated to the jobId
/// This endpoint returns the solution of a large problems. You can fetch it with the job_id, you have been sent.
///
/// @param key your API key
/// @param jobId Request solution with jobId
/// 
///
/// @return SWGResponse*
-(NSNumber*) getSolutionWithCompletionBlock :(NSString*) key 
     jobId:(NSString*) jobId 
    
    completionHandler: (void (^)(SWGResponse* output, NSError* error))completionBlock;
    



@end
