#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGTimeWindow.h"
#import "SWGAddress.h"


@protocol SWGService
@end

@interface SWGService : SWGObject

/* Unique identifier of service [optional]
 */
@property(nonatomic) NSString* _id;
/* type of service [optional]
 */
@property(nonatomic) NSString* type;
/* name of service [optional]
 */
@property(nonatomic) NSString* name;

@property(nonatomic) SWGAddress* address;
/* duration of service, i.e. time in ms the corresponding activity takes [optional]
 */
@property(nonatomic) NSNumber* duration;
/* array of time windows. currently, only a single time window is allowed [optional]
 */
@property(nonatomic) NSArray<SWGTimeWindow>* timeWindows;
/* array of capacity dimensions [optional]
 */
@property(nonatomic) NSArray* /* NSNumber */ size;
/* array of required skills [optional]
 */
@property(nonatomic) NSArray* /* NSString */ requiredSkills;
/* array of allowed vehicle ids [optional]
 */
@property(nonatomic) NSArray* /* NSString */ allowedVehicles;

@end
