#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGRoute.h"


@protocol SWGSolution
@end

@interface SWGSolution : SWGObject

/* overall costs of solution [optional]
 */
@property(nonatomic) NSNumber* costs;
/* overall travel distance in meters [optional]
 */
@property(nonatomic) NSNumber* distance;
/* overall travel time in ms [optional]
 */
@property(nonatomic) NSNumber* time;
/* number of jobs that could not be assigned to final solution [optional]
 */
@property(nonatomic) NSNumber* noUnassigned;
/* An array of routes [optional]
 */
@property(nonatomic) NSArray<SWGRoute>* routes;

@property(nonatomic) NSObject* unassigned;

@end
