#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGTimeWindow.h"
#import "SWGAddress.h"


@protocol SWGStop
@end

@interface SWGStop : SWGObject


@property(nonatomic) SWGAddress* address;
/* duration of stop, i.e. time in ms the corresponding activity takes [optional]
 */
@property(nonatomic) NSNumber* duration;
/* array of time windows. currently, only a single time window is allowed [optional]
 */
@property(nonatomic) NSArray<SWGTimeWindow>* timeWindows;

@end
