#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGAddress.h"
#import "SWGBreak.h"


@protocol SWGVehicle
@end

@interface SWGVehicle : SWGObject

/* Unique identifier of vehicle [optional]
 */
@property(nonatomic) NSString* vehicleId;
/* Unique identifier referring to the available vehicle types [optional]
 */
@property(nonatomic) NSString* typeId;

@property(nonatomic) SWGAddress* startAddress;

@property(nonatomic) SWGAddress* endAddress;

@property(nonatomic) SWGBreak* _break;
/* Indicates whether vehicle should return to start address or not. If not, it can end at any service activity. [optional]
 */
@property(nonatomic) NSNumber* returnToDepot;
/* earliest start of vehicle at its start location [optional]
 */
@property(nonatomic) NSNumber* earliestStart;
/* latest end of vehicle at its end location [optional]
 */
@property(nonatomic) NSNumber* latestEnd;
/* array of skills [optional]
 */
@property(nonatomic) NSArray* /* NSString */ skills;

@end
