#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGVehicleType
@end

@interface SWGVehicleType : SWGObject

/* Unique identifier for the vehicle type [optional]
 */
@property(nonatomic) NSString* typeId;
/* Profile of vehicle type [optional]
 */
@property(nonatomic) NSString* profile;
/* array of capacity dimensions [optional]
 */
@property(nonatomic) NSArray* /* NSNumber */ capacity;
/* speed_factor of vehicle type [optional]
 */
@property(nonatomic) NSNumber* speedFactor;
/* service time factor of vehicle type [optional]
 */
@property(nonatomic) NSNumber* serviceTimeFactor;

@end
