#import <Foundation/Foundation.h>
#import "SWGRequest.h"
#import "SWGJobId.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGVrpApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGVrpApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGVrpApi*) sharedAPI;
///
///
/// Solves large routing problems
/// This endpoint solves large problems, i.e. traveling salesman or vehicle routing problems, and returns the solution.
///
/// @param key your API key
/// @param body Request object that contains the problem to be solved
/// 
///
/// @return SWGJobId*
-(NSNumber*) postVrpWithCompletionBlock :(NSString*) key 
     body:(SWGRequest*) body 
    
    completionHandler: (void (^)(SWGJobId* output, NSError* error))completionBlock;
    



@end
