# coding: utf-8

"""
    Route Optimization API

    Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.activity import Activity
from .models.address import Address
from .models.algorithm import Algorithm
from .models.cost_matrix import CostMatrix
from .models.job_id import JobId
from .models.model_break import ModelBreak
from .models.objective import Objective
from .models.relation import Relation
from .models.request import Request
from .models.response import Response
from .models.route import Route
from .models.service import Service
from .models.shipment import Shipment
from .models.solution import Solution
from .models.solution_unassigned import SolutionUnassigned
from .models.stop import Stop
from .models.time_window import TimeWindow
from .models.vehicle import Vehicle
from .models.vehicle_type import VehicleType

# import apis into sdk package
from .apis.solution_api import SolutionApi
from .apis.vrp_api import VrpApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
