/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGAlgorithm.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGAlgorithm::SWGAlgorithm(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAlgorithm::SWGAlgorithm() {
    init();
}

SWGAlgorithm::~SWGAlgorithm() {
    this->cleanup();
}

void
SWGAlgorithm::init() {
    problem_type = new QString("");
objective = new QString("");
}

void
SWGAlgorithm::cleanup() {
    if(problem_type != NULL) {
        delete problem_type;
    }
if(objective != NULL) {
        delete objective;
    }
}

SWGAlgorithm*
SWGAlgorithm::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAlgorithm::fromJsonObject(QJsonObject &pJson) {
    setValue(&problem_type, pJson["problem_type"], "QString", "QString");
setValue(&objective, pJson["objective"], "QString", "QString");
}

QString
SWGAlgorithm::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGAlgorithm::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("problem_type"), problem_type, obj, QString("QString"));
    
        

    
    toJsonValue(QString("objective"), objective, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGAlgorithm::getProblemType() {
    return problem_type;
}
void
SWGAlgorithm::setProblemType(QString* problem_type) {
    this->problem_type = problem_type;
}

QString*
SWGAlgorithm::getObjective() {
    return objective;
}
void
SWGAlgorithm::setObjective(QString* objective) {
    this->objective = objective;
}



} /* namespace Swagger */

