/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGBreak.h
 * 
 * 
 */

#ifndef SWGBreak_H_
#define SWGBreak_H_

#include <QJsonObject>


#include <QList>

#include "SWGObject.h"


namespace Swagger {

class SWGBreak: public SWGObject {
public:
    SWGBreak();
    SWGBreak(QString* json);
    virtual ~SWGBreak();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGBreak* fromJson(QString &jsonString);

    qint64 getEarliest();
    void setEarliest(qint64 earliest);
qint64 getLatest();
    void setLatest(qint64 latest);
qint64 getDuration();
    void setDuration(qint64 duration);
qint64 getMaxDrivingTime();
    void setMaxDrivingTime(qint64 max_driving_time);
qint64 getInitialDrivingTime();
    void setInitialDrivingTime(qint64 initial_driving_time);
QList<qint64>* getPossibleSplit();
    void setPossibleSplit(QList<qint64>* possible_split);

private:
    qint64 earliest;
qint64 latest;
qint64 duration;
qint64 max_driving_time;
qint64 initial_driving_time;
QList<qint64>* possible_split;
};

} /* namespace Swagger */

#endif /* SWGBreak_H_ */
