/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCostMatrix.h
 * 
 * 
 */

#ifndef SWGCostMatrix_H_
#define SWGCostMatrix_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGCostMatrix: public SWGObject {
public:
    SWGCostMatrix();
    SWGCostMatrix(QString* json);
    virtual ~SWGCostMatrix();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCostMatrix* fromJson(QString &jsonString);

    QString* getType();
    void setType(QString* type);

    QString* getUrl();
    void setUrl(QString* url);

    QString* getProfile();
    void setProfile(QString* profile);


private:
    QString* type;
    QString* url;
    QString* profile;
};

} /* namespace Swagger */

#endif /* SWGCostMatrix_H_ */
