/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGJobId.h
 * 
 * 
 */

#ifndef SWGJobId_H_
#define SWGJobId_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGJobId: public SWGObject {
public:
    SWGJobId();
    SWGJobId(QString* json);
    virtual ~SWGJobId();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGJobId* fromJson(QString &jsonString);

    QString* getJobId();
    void setJobId(QString* job_id);


private:
    QString* job_id;
};

} /* namespace Swagger */

#endif /* SWGJobId_H_ */
