/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGJobId.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGJobId::SWGJobId(QString* json) {
    init();
    this->fromJson(*json);
}

SWGJobId::SWGJobId() {
    init();
}

SWGJobId::~SWGJobId() {
    this->cleanup();
}

void
SWGJobId::init() {
    job_id = new QString("");
}

void
SWGJobId::cleanup() {
    if(job_id != NULL) {
        delete job_id;
    }
}

SWGJobId*
SWGJobId::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGJobId::fromJsonObject(QJsonObject &pJson) {
    setValue(&job_id, pJson["job_id"], "QString", "QString");
}

QString
SWGJobId::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGJobId::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("job_id"), job_id, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGJobId::getJobId() {
    return job_id;
}
void
SWGJobId::setJobId(QString* job_id) {
    this->job_id = job_id;
}



} /* namespace Swagger */

