/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGObjective.h
 * 
 * 
 */

#ifndef SWGObjective_H_
#define SWGObjective_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGObjective: public SWGObject {
public:
    SWGObjective();
    SWGObjective(QString* json);
    virtual ~SWGObjective();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGObjective* fromJson(QString &jsonString);

    QString* getType();
    void setType(QString* type);

    QString* getValue();
    void setValue(QString* value);


private:
    QString* type;
    QString* value;
};

} /* namespace Swagger */

#endif /* SWGObjective_H_ */
