/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGObjective.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGObjective::SWGObjective(QString* json) {
    init();
    this->fromJson(*json);
}

SWGObjective::SWGObjective() {
    init();
}

SWGObjective::~SWGObjective() {
    this->cleanup();
}

void
SWGObjective::init() {
    type = new QString("");
value = new QString("");
}

void
SWGObjective::cleanup() {
    if(type != NULL) {
        delete type;
    }
if(value != NULL) {
        delete value;
    }
}

SWGObjective*
SWGObjective::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGObjective::fromJsonObject(QJsonObject &pJson) {
    setValue(&type, pJson["type"], "QString", "QString");
setValue(&value, pJson["value"], "QString", "QString");
}

QString
SWGObjective::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGObjective::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("type"), type, obj, QString("QString"));
    
        

    
    toJsonValue(QString("value"), value, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGObjective::getType() {
    return type;
}
void
SWGObjective::setType(QString* type) {
    this->type = type;
}

QString*
SWGObjective::getValue() {
    return value;
}
void
SWGObjective::setValue(QString* value) {
    this->value = value;
}



} /* namespace Swagger */

