/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGRoute.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGRoute::SWGRoute(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRoute::SWGRoute() {
    init();
}

SWGRoute::~SWGRoute() {
    this->cleanup();
}

void
SWGRoute::init() {
    vehicle_id = new QString("");
activities = new QList<SWGActivity*>();
}

void
SWGRoute::cleanup() {
    if(vehicle_id != NULL) {
        delete vehicle_id;
    }
if(activities != NULL) {
        QList<SWGActivity*>* arr = activities;
        foreach(SWGActivity* o, *arr) {
            delete o;
        }
        delete activities;
    }
}

SWGRoute*
SWGRoute::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRoute::fromJsonObject(QJsonObject &pJson) {
    setValue(&vehicle_id, pJson["vehicle_id"], "QString", "QString");
setValue(&activities, pJson["activities"], "QList", "SWGActivity");
}

QString
SWGRoute::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRoute::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("vehicle_id"), vehicle_id, obj, QString("QString"));
    
        

    
    QList<SWGActivity*>* activitiesList = activities;
    QJsonArray activitiesJsonArray;
    toJsonArray((QList<void*>*)activities, &activitiesJsonArray, "activities", "SWGActivity");

    obj->insert("activities", activitiesJsonArray);
    

    return obj;
}

QString*
SWGRoute::getVehicleId() {
    return vehicle_id;
}
void
SWGRoute::setVehicleId(QString* vehicle_id) {
    this->vehicle_id = vehicle_id;
}

QList<SWGActivity*>*
SWGRoute::getActivities() {
    return activities;
}
void
SWGRoute::setActivities(QList<SWGActivity*>* activities) {
    this->activities = activities;
}



} /* namespace Swagger */

