/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGSolutionApi_H_
#define _SWG_SWGSolutionApi_H_

#include "SWGHttpRequest.h"

#include <QString>
#include "SWGResponse.h"

#include <QObject>

namespace Swagger {

class SWGSolutionApi: public QObject {
    Q_OBJECT

public:
    SWGSolutionApi();
    SWGSolutionApi(QString host, QString basePath);
    ~SWGSolutionApi();

    QString host;
    QString basePath;

    void getSolution(QString* key, QString* job_id);
    
private:
    void getSolutionCallback (HttpRequestWorker * worker);
    
signals:
    void getSolutionSignal(SWGResponse* summary);
    
};
}
#endif
