/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGVrpApi_H_
#define _SWG_SWGVrpApi_H_

#include "SWGHttpRequest.h"

#include <QString>
#include "SWGJobId.h"
#include "SWGRequest.h"

#include <QObject>

namespace Swagger {

class SWGVrpApi: public QObject {
    Q_OBJECT

public:
    SWGVrpApi();
    SWGVrpApi(QString host, QString basePath);
    ~SWGVrpApi();

    QString host;
    QString basePath;

    void postVrp(QString* key, SWGRequest body);
    
private:
    void postVrpCallback (HttpRequestWorker * worker);
    
signals:
    void postVrpSignal(SWGJobId* summary);
    
};
}
#endif
