=begin
#Route Optimization API

#Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for GraphHopper::SolutionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SolutionApi' do
  before do
    # run before each test
    @instance = GraphHopper::SolutionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SolutionApi' do
    it 'should create an instact of SolutionApi' do
      expect(@instance).to be_instance_of(GraphHopper::SolutionApi)
    end
  end

  # unit tests for get_solution
  # Return the solution associated to the jobId
  # This endpoint returns the solution of a large problems. You can fetch it with the job_id, you have been sent. 
  # @param key your API key
  # @param job_id Request solution with jobId
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'get_solution test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
