//
// Activity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Activity: JSONEncodable {

    public enum SwaggerType: String { 
        case Start = "start"
        case End = "end"
        case Service = "service"
        case Pickupshipment = "pickupShipment"
        case Delivershipment = "deliverShipment"
    }
    
    /** type of activity */
    public var type: SwaggerType?
    /** id referring to the underlying service or shipment, i.e. the shipment or service this activity belongs to */
    public var id: String?
    /** id that refers to address */
    public var location_id: String?
    /** arrival time at this activity in ms */
    public var arr_time: Int?
    /** end time of and thus departure time at this activity */
    public var end_time: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["id"] = self.id
        nillableDictionary["location_id"] = self.location_id
        nillableDictionary["arr_time"] = self.arr_time
        nillableDictionary["end_time"] = self.end_time
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
