//
// Algorithm.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Algorithm: JSONEncodable {

    public enum Problem_type: String { 
        case Min = "min"
        case MinMax = "min-max"
    }
    
    public enum Objective: String { 
        case TransportTime = "transport_time"
        case CompletionTime = "completion_time"
    }
    
    public var problem_type: Problem_type?
    public var objective: Objective?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["problem_type"] = self.problem_type?.rawValue
        nillableDictionary["objective"] = self.objective?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
