//
// Relation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Relation: JSONEncodable {

    /** identifier of relation */
    public var type: String?
    /** An array of ids that should be related */
    public var ids: [String]?
    /** vehicle id */
    public var vehicle_id: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["type"] = self.type
        nillableDictionary["ids"] = self.ids?.encodeToJSON()
        nillableDictionary["vehicle_id"] = self.vehicle_id
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
