//
// TimeWindow.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TimeWindow: JSONEncodable {

    /** earliest start time of corresponding activity */
    public var earliest: Int?
    /** latest start time of corresponding activity */
    public var latest: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["earliest"] = self.earliest
        nillableDictionary["latest"] = self.latest
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
