//
// VehicleType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class VehicleType: JSONEncodable {

    public enum Profile: String { 
        case Car = "car"
        case Bike = "bike"
        case Foot = "foot"
        case Mtb = "mtb"
        case Motorcycle = "motorcycle"
        case Racingbike = "racingbike"
        case Truck = "truck"
        case SmallTruck = "small_truck"
        case Bus = "bus"
    }
    
    /** Unique identifier for the vehicle type */
    public var type_id: String?
    /** Profile of vehicle type */
    public var profile: Profile?
    /** array of capacity dimensions */
    public var capacity: [Int]?
    /** speed_factor of vehicle type */
    public var speed_factor: Double?
    /** service time factor of vehicle type */
    public var service_time_factor: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["type_id"] = self.type_id
        nillableDictionary["profile"] = self.profile?.rawValue
        nillableDictionary["capacity"] = self.capacity?.encodeToJSON()
        nillableDictionary["speed_factor"] = self.speed_factor
        nillableDictionary["service_time_factor"] = self.service_time_factor
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
