/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type Activity struct {

	// type of activity
	Type_ string `json:"type,omitempty"`

	// id referring to the underlying service or shipment, i.e. the shipment or service this activity belongs to
	Id string `json:"id,omitempty"`

	// id that refers to address
	LocationId string `json:"location_id,omitempty"`

	// arrival time at this activity in ms
	ArrTime int64 `json:"arr_time,omitempty"`

	// end time of and thus departure time at this activity
	EndTime int64 `json:"end_time,omitempty"`

	// waiting time at this activity in ms
	WaitingTime int64 `json:"waiting_time,omitempty"`

	// cumulated distance from start to this activity in m
	Distance int64 `json:"distance,omitempty"`

	// driving time of driver in ms
	DrivingTime int64 `json:"driving_time,omitempty"`

	// Array with size/capacity dimensions before this activity
	LoadBefore []int32 `json:"load_before,omitempty"`

	// Array with size/capacity dimensions after this activity
	LoadAfter []int32 `json:"load_after,omitempty"`
}
