/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type CostMatrix struct {

	// type of cost matrix, currently default or google are supported
	Type_ string `json:"type,omitempty"`

	// URL of matrix service
	Url string `json:"url,omitempty"`

	// vehicle profile or empty if catch all fallback
	Profile string `json:"profile,omitempty"`
}
