/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type Objective struct {

	// type of objective function, i.e. min or min-max 
	Type_ string `json:"type,omitempty"`

	// objective function value
	Value string `json:"value,omitempty"`
}
