/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type Relation struct {

	// identifier of relation
	Type_ string `json:"type,omitempty"`

	// An array of ids that should be related
	Ids []string `json:"ids,omitempty"`

	// vehicle id
	VehicleId string `json:"vehicle_id,omitempty"`
}
