/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type Request struct {

	// An array of vehicles that can be employed
	Vehicles []Vehicle `json:"vehicles,omitempty"`

	// An array of vehicle types
	VehicleTypes []VehicleType `json:"vehicle_types,omitempty"`

	// An array of services
	Services []Service `json:"services,omitempty"`

	// An array of shipments
	Shipments []Shipment `json:"shipments,omitempty"`

	// An array of relations
	Relations []Relation `json:"relations,omitempty"`

	Algorithm Algorithm `json:"algorithm,omitempty"`

	// An array of objectives
	Objectives []Objective `json:"objectives,omitempty"`

	// An array of cost matrices
	CostMatrices []CostMatrix `json:"cost_matrices,omitempty"`
}
