/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graphhopper

type Response struct {

	Copyrights []string `json:"copyrights,omitempty"`

	// unique identify of job - which you get when posting your request to the large problem solver
	JobId string `json:"job_id,omitempty"`

	// indicates the current status of the job
	Status string `json:"status,omitempty"`

	// waiting time in ms
	WaitingInQueue int64 `json:"waiting_in_queue,omitempty"`

	// processing time in ms. if job is still waiting in queue, processing_time is 0
	ProcessingTime int64 `json:"processing_time,omitempty"`

	// the solution. only available if status field indicates finished
	Solution Solution `json:"solution,omitempty"`
}
