/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graphhopper

type Route struct {

	// id of vehicle that operates route
	VehicleId string `json:"vehicle_id,omitempty"`

	// distance of route in meter
	Distance int64 `json:"distance,omitempty"`

	// transport time of route in ms
	TransportTime int64 `json:"transport_time,omitempty"`

	// completion time of route in ms
	CompletionTime int64 `json:"completion_time,omitempty"`

	// waiting time of route in ms
	WaitingTime int64 `json:"waiting_time,omitempty"`

	// array of activities
	Activities []Activity `json:"activities,omitempty"`
}
