/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graphhopper

type Solution struct {

	// overall costs of solution
	Costs int32 `json:"costs,omitempty"`

	// overall travel distance in meters
	Distance int32 `json:"distance,omitempty"`

	// overall transport time in ms
	Time int64 `json:"time,omitempty"`

	// overall transport time in ms
	TransportTime int64 `json:"transport_time,omitempty"`

	// operation time of the longest route in ms
	MaxOperationTime int64 `json:"max_operation_time,omitempty"`

	// total waiting time in ms
	WaitingTime int64 `json:"waiting_time,omitempty"`

	// number of employed vehicles
	NoVehicles int32 `json:"no_vehicles,omitempty"`

	// number of jobs that could not be assigned to final solution
	NoUnassigned int32 `json:"no_unassigned,omitempty"`

	// An array of routes
	Routes []Route `json:"routes,omitempty"`

	Unassigned SolutionUnassigned `json:"unassigned,omitempty"`
}
