/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type Stop struct {

	Address Address `json:"address,omitempty"`

	// duration of stop, i.e. time in ms the corresponding activity takes
	Duration int64 `json:"duration,omitempty"`

	// array of time windows. currently, only a single time window is allowed
	TimeWindows []TimeWindow `json:"time_windows,omitempty"`
}
