/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type TimeWindow struct {

	// earliest start time of corresponding activity
	Earliest int64 `json:"earliest,omitempty"`

	// latest start time of corresponding activity
	Latest int64 `json:"latest,omitempty"`
}
