/* 
 * Route Optimization API
 *
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graphhopper

type VehicleType struct {

	// Unique identifier for the vehicle type
	TypeId string `json:"type_id,omitempty"`

	// Profile of vehicle type
	Profile string `json:"profile,omitempty"`

	// array of capacity dimensions
	Capacity []int32 `json:"capacity,omitempty"`

	// speed_factor of vehicle type
	SpeedFactor float64 `json:"speed_factor,omitempty"`

	// service time factor of vehicle type
	ServiceTimeFactor float64 `json:"service_time_factor,omitempty"`
}
