#import <Foundation/Foundation.h>
#import "SWGResponse.h"
#import "SWGApi.h"

/**
* Route Optimization API
* Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGSolutionApi: NSObject <SWGApi>

extern NSString* kSWGSolutionApiErrorDomain;
extern NSInteger kSWGSolutionApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Return the solution associated to the jobId
/// This endpoint returns the solution of a large problems. You can fetch it with the job_id, you have been sent. 
///
/// @param key your API key
/// @param jobId Request solution with jobId
/// 
///  code:200 message:"A response containing the solution",
///  code:400 message:"Error occurred on client side such as invalid input.",
///  code:500 message:"Error occurred on server side."
///
/// @return SWGResponse*
-(NSNumber*) getSolutionWithKey: (NSString*) key
    jobId: (NSString*) jobId
    completionHandler: (void (^)(SWGResponse* output, NSError* error)) handler;



@end
