//
// VrpAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension GraphHopperAPI {
    
    public class VrpAPI: APIBase {
    
        /**
         
         Solves large routing problems
         
         - POST /optimize
         - This endpoint solves large problems, i.e. traveling salesman or vehicle routing problems, and returns the solution.
         - API Key:
           - type: apiKey key (QUERY)
           - name: api_key
         - examples: [{example={
  "job_id" : "aeiou"
}, contentType=application/json}]
         
         - parameter key: (query) your API key
         - parameter body: (body) Request object that contains the problem to be solved

         - returns: RequestBuilder<JobId> 
         */
        public class func postVrp(key key: String, body: Request) -> RequestBuilder<JobId> {
            let path = "/optimize"
            let URLString = GraphHopperAPI.basePath + path
            
            let parameters = body.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<JobId>.Type = GraphHopperAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
        }
    
    }
}
