# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Algorithm(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Algorithm - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'problem_type': 'str',
            'objective': 'str'
        }

        self.attribute_map = {
            'problem_type': 'problem_type',
            'objective': 'objective'
        }

        self._problem_type = None
        self._objective = None

    @property
    def problem_type(self):
        """
        Gets the problem_type of this Algorithm.


        :return: The problem_type of this Algorithm.
        :rtype: str
        """
        return self._problem_type

    @problem_type.setter
    def problem_type(self, problem_type):
        """
        Sets the problem_type of this Algorithm.


        :param problem_type: The problem_type of this Algorithm.
        :type: str
        """
        allowed_values = ["min", "min-max"]
        if problem_type not in allowed_values:
            raise ValueError(
                "Invalid value for `problem_type`, must be one of {0}"
                .format(allowed_values)
            )
        self._problem_type = problem_type

    @property
    def objective(self):
        """
        Gets the objective of this Algorithm.


        :return: The objective of this Algorithm.
        :rtype: str
        """
        return self._objective

    @objective.setter
    def objective(self, objective):
        """
        Sets the objective of this Algorithm.


        :param objective: The objective of this Algorithm.
        :type: str
        """
        allowed_values = ["transport_time", "completion_time"]
        if objective not in allowed_values:
            raise ValueError(
                "Invalid value for `objective`, must be one of {0}"
                .format(allowed_values)
            )
        self._objective = objective

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()
