# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Shipment(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Shipment - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'pickup': 'Stop',
            'delivery': 'Stop',
            'size': 'list[int]',
            'required_skills': 'list[str]',
            'allowed_vehicles': 'list[str]'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'pickup': 'pickup',
            'delivery': 'delivery',
            'size': 'size',
            'required_skills': 'required_skills',
            'allowed_vehicles': 'allowed_vehicles'
        }

        self._id = None
        self._name = None
        self._pickup = None
        self._delivery = None
        self._size = None
        self._required_skills = None
        self._allowed_vehicles = None

    @property
    def id(self):
        """
        Gets the id of this Shipment.
        Unique identifier of service

        :return: The id of this Shipment.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Shipment.
        Unique identifier of service

        :param id: The id of this Shipment.
        :type: str
        """
        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Shipment.
        name of shipment

        :return: The name of this Shipment.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Shipment.
        name of shipment

        :param name: The name of this Shipment.
        :type: str
        """
        self._name = name

    @property
    def pickup(self):
        """
        Gets the pickup of this Shipment.


        :return: The pickup of this Shipment.
        :rtype: Stop
        """
        return self._pickup

    @pickup.setter
    def pickup(self, pickup):
        """
        Sets the pickup of this Shipment.


        :param pickup: The pickup of this Shipment.
        :type: Stop
        """
        self._pickup = pickup

    @property
    def delivery(self):
        """
        Gets the delivery of this Shipment.


        :return: The delivery of this Shipment.
        :rtype: Stop
        """
        return self._delivery

    @delivery.setter
    def delivery(self, delivery):
        """
        Sets the delivery of this Shipment.


        :param delivery: The delivery of this Shipment.
        :type: Stop
        """
        self._delivery = delivery

    @property
    def size(self):
        """
        Gets the size of this Shipment.
        array of capacity dimensions

        :return: The size of this Shipment.
        :rtype: list[int]
        """
        return self._size

    @size.setter
    def size(self, size):
        """
        Sets the size of this Shipment.
        array of capacity dimensions

        :param size: The size of this Shipment.
        :type: list[int]
        """
        self._size = size

    @property
    def required_skills(self):
        """
        Gets the required_skills of this Shipment.
        array of required skills

        :return: The required_skills of this Shipment.
        :rtype: list[str]
        """
        return self._required_skills

    @required_skills.setter
    def required_skills(self, required_skills):
        """
        Sets the required_skills of this Shipment.
        array of required skills

        :param required_skills: The required_skills of this Shipment.
        :type: list[str]
        """
        self._required_skills = required_skills

    @property
    def allowed_vehicles(self):
        """
        Gets the allowed_vehicles of this Shipment.
        array of allowed vehicle ids

        :return: The allowed_vehicles of this Shipment.
        :rtype: list[str]
        """
        return self._allowed_vehicles

    @allowed_vehicles.setter
    def allowed_vehicles(self, allowed_vehicles):
        """
        Sets the allowed_vehicles of this Shipment.
        array of allowed vehicle ids

        :param allowed_vehicles: The allowed_vehicles of this Shipment.
        :type: list[str]
        """
        self._allowed_vehicles = allowed_vehicles

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()
